[34.978628159] 2018-11-07 13:28:02,300 - INFO - launcher: Starting sanity checks
[35.977125168] 2018-11-07 13:28:02,301 - INFO - launcher: Checking for Python 3.5+
[35.977125168] 2018-11-07 13:28:02,301 - INFO - launcher: Checking console encoding
[35.977125168] 2018-11-07 13:28:02,301 - INFO - launcher: Setting console encoding to UTF-8
[35.977125168] 2018-11-07 13:28:02,301 - INFO - launcher: Ensuring we're in the right environment
[36.975860596] 2018-11-07 13:28:02,302 - INFO - launcher: Adding local bins/ folder to path
[726.551771164] 2018-11-07 13:28:02,991 - INFO - launcher: Required checks passed.
[728.550672531] 2018-11-07 13:28:02,993 - INFO - launcher: Optional checks passed.
[728.550672531] 2018-11-07 13:28:02,993 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1.4761354923248291] 2018-11-07 13:28:03,741 - WARNING - musicbot.config | In config.py::MainThread(3936), line 113 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[1.4761354923248291] 2018-11-07 13:28:03,741 - INFO - musicbot.config | In config.py::MainThread(3936), line 124 in run_checks: Using i18n: config/i18n/en.json
[1.4771354198455811] 2018-11-07 13:28:03,742 - WARNING - musicbot.config | In config.py::MainThread(3936), line 207 in create_empty_file_ifnoexist: Creating config/blacklist.txt
[1.4771354198455811] 2018-11-07 13:28:03,742 - WARNING - musicbot.config | In config.py::MainThread(3936), line 207 in create_empty_file_ifnoexist: Creating config/whitelist.txt
[1.4791336059570312] 2018-11-07 13:28:03,744 - DEBUG - musicbot.config | In config.py::MainThread(3936), line 294 in find_autoplaylist: Copying _autoplaylist.txt to autoplaylist.txt
[1.4801332950592041] 2018-11-07 13:28:03,745 - INFO - musicbot.permissions | In permissions.py::MainThread(3936), line 40 in __init__: Permissions file not found, copying example_permissions.ini
[1.4841301441192627] 2018-11-07 13:28:03,749 - DEBUG - musicbot.json | In json.py::MainThread(3936), line 8 in __init__: Init JSON obj with config/i18n/en.json
[1.5490918159484863] 2018-11-07 13:28:03,814 - DEBUG - musicbot.bot | In bot.py::MainThread(3936), line 223 in _setup_logging: Set logging level to INFO
[1.5490918159484863] 2018-11-07 13:28:03,814 - INFO - musicbot.bot | In bot.py::MainThread(3936), line 83 in __init__: Starting MusicBot 1.9.8_1
[1.5500912666320801] 2018-11-07 13:28:03,815 - INFO - musicbot.bot | In bot.py::MainThread(3936), line 89 in __init__: Loaded autoplaylist with 2531 entries
[7.8515787124633789] 2018-11-07 13:28:10,116 - DEBUG - musicbot.bot | In bot.py::MainThread(3936), line 913 in on_ready: Connection established, ready to go.
[7.8515787124633789] 2018-11-07 13:28:10,116 - DEBUG - musicbot.bot | In bot.py::MainThread(3936), line 334 in _cache_app_info: Caching app info
[8.2295982837677002] 2018-11-07 13:28:10,494 - DEBUG - musicbot.bot | In bot.py::MainThread(3936), line 735 in _scheck_ensure_env: Ensuring data folders exist
[8.2305979728698730] 2018-11-07 13:28:10,495 - DEBUG - musicbot.bot | In bot.py::MainThread(3936), line 751 in _scheck_server_permissions: Checking server permissions
[8.2305979728698730] 2018-11-07 13:28:10,495 - DEBUG - musicbot.bot | In bot.py::MainThread(3936), line 755 in _scheck_autoplaylist: Auditing autoplaylist
[8.2305979728698730] 2018-11-07 13:28:10,495 - DEBUG - musicbot.bot | In bot.py::MainThread(3936), line 759 in _scheck_configs: Validating config
[8.2305979728698730] 2018-11-07 13:28:10,495 - DEBUG - musicbot.config | In config.py::MainThread(3936), line 213 in async_validate: Validating options...
[8.2305979728698730] 2018-11-07 13:28:10,495 - DEBUG - musicbot.config | In config.py::MainThread(3936), line 227 in async_validate: Acquired owner id via API
[8.2305979728698730] 2018-11-07 13:28:10,495 - DEBUG - musicbot.bot | In bot.py::MainThread(3936), line 762 in _scheck_configs: Validating permissions config
[8.2305979728698730] 2018-11-07 13:28:10,495 - DEBUG - musicbot.permissions | In permissions.py::MainThread(3936), line 65 in async_validate: Validating permissions...
[8.2305979728698730] 2018-11-07 13:28:10,495 - DEBUG - musicbot.permissions | In permissions.py::MainThread(3936), line 69 in async_validate: Fixing automatic owner group
[8.2305979728698730] 2018-11-07 13:28:10,495 - INFO - musicbot.bot | In bot.py::MainThread(3936), line 930 in on_ready: Connected: 507923150588215321/LOT music#1822
[8.2325980663299561] 2018-11-07 13:28:10,497 - INFO - musicbot.bot | In bot.py::MainThread(3936), line 938 in on_ready: Owner:     394048203072339970/ANI-IN#1150

[8.2325980663299561] 2018-11-07 13:28:10,497 - INFO - musicbot.bot | In bot.py::MainThread(3936), line 941 in on_ready: Guild List:
[8.2335972785949707] 2018-11-07 13:28:10,498 - INFO - musicbot.bot | In bot.py::MainThread(3936), line 944 in on_ready:  - |L.O.T| Legends Of Tomorrow
[8.2335972785949707] 2018-11-07 13:28:10,498 - INFO - musicbot.bot | In bot.py::MainThread(3936), line 990 in on_ready: Not bound to any text channels
[8.2345964908599854] 2018-11-07 13:28:10,499 - INFO - musicbot.bot | In bot.py::MainThread(3936), line 1016 in on_ready: Not autojoining any voice channels
[126.5131452083587646] 2018-11-07 13:30:08,778 - ERROR - musicbot.bot | In bot.py::MainThread(3936), line 901 in on_error: Exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Users\ANI-IN\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ANI-IN\Desktop\New folder\MusicBot\musicbot\bot.py", line 2796, in on_voice_state_update
    player = await self.get_player(channel)
  File "C:\Users\ANI-IN\Desktop\New folder\MusicBot\musicbot\bot.py", line 425, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
[158.3272922039031982] 2018-11-07 13:30:40,592 - INFO - musicbot.bot | In bot.py::MainThread(3936), line 2598 in on_message: 394048203072339970/ANI-IN#1150: !summon
[159.5930016040802002] 2018-11-07 13:30:41,858 - DEBUG - musicbot.bot | In bot.py::MainThread(3936), line 509 in on_player_finished_playing: Running on_player_finished_playing
[159.5930016040802002] 2018-11-07 13:30:41,858 - DEBUG - musicbot.bot | In bot.py::MainThread(3936), line 524 in on_player_finished_playing: No content in current autoplaylist. Filling with new music...
[159.6049954891204834] 2018-11-07 13:30:41,870 - DEBUG - musicbot.bot | In bot.py::MainThread(3936), line 505 in on_player_stop: Running on_player_stop
[165.6561000347137451] 2018-11-07 13:30:47,921 - DEBUG - musicbot.entry | In entry.py::MainThread(3936), line 56 in get_ready_future: Created future for None
[165.6561000347137451] 2018-11-07 13:30:47,921 - INFO - musicbot.bot | In bot.py::MainThread(3936), line 1864 in cmd_summon: Joining |L.O.T| Legends Of Tomorrow/Lounge (1)
[165.6580994129180908] 2018-11-07 13:30:47,923 - DEBUG - musicbot.bot | In bot.py::MainThread(3936), line 586 in on_player_entry_added: Running on_player_entry_added
[165.6590991020202637] 2018-11-07 13:30:47,924 - INFO - musicbot.entry | In entry.py::MainThread(3936), line 285 in _really_download: Download started: https://youtube.com/watch?v=x0q8Oho_RjM
[167.6619174480438232] 2018-11-07 13:30:49,927 - DEBUG - musicbot.entry | In entry.py::MainThread(3936), line 56 in get_ready_future: Created future for None
[169.5190677642822266] 2018-11-07 13:30:51,784 - INFO - musicbot.entry | In entry.py::MainThread(3936), line 295 in _really_download: Download complete: https://youtube.com/watch?v=x0q8Oho_RjM
[169.5240635871887207] 2018-11-07 13:30:51,789 - FFMPEG - musicbot.player | In player.py::MainThread(3936), line 276 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-x0q8Oho_RjM-I_Drink_Alone_-_George_Thorogood.webm
[169.8383514881134033] 2018-11-07 13:30:52,103 - DEBUG - musicbot.player | In player.py::MainThread(3936), line 287 in _play: Playing <discord.player.PCMVolumeTransformer object at 0x04D0EB10> using <discord.voice_client.VoiceClient object at 0x04D0ED90>
[169.8435339927673340] 2018-11-07 13:30:52,108 - DEBUG - musicbot.bot | In bot.py::MainThread(3936), line 452 in on_player_play: Running on_player_play
[169.8435339927673340] 2018-11-07 13:30:52,108 - DEBUG - musicbot.bot | In bot.py::MainThread(3936), line 671 in serialize_queue: Serializing queue for 346548445768843264
